### ISSUE TITLE
Ошибки при компиляции.

### ISSUE THREAD

**Issue by UUSR** [3s3s/simple_server#3]
Уважаемый @3s3s ,
Получил странную ошибку при сборке вашего проекта:

> Ошибка
>     1   error C1083: Не удается открыть файл включение: curlbuild.h: No such file or directory c:\uusr\simple_server-master\curl\include\curl\curl.h   34  1   ssl_test
> Предупреждение    2   warning C4245: return: преобразование "int" в "unsigned __int64", несоответствие типов со знаком и без    c:\uusr\simple_server-master\ssl_test\sendfile.cpp  33  1   ssl_test
> Предупреждение    3   warning C4245: return: преобразование "int" в "unsigned __int64", несоответствие типов со знаком и без    c:\uusr\simple_server-master\ssl_test\sendfile.cpp  40  1   ssl_test
> Предупреждение    4   warning C4245: return: преобразование "int" в "unsigned __int64", несоответствие типов со знаком и без    c:\uusr\simple_server-master\ssl_test\sendfile.cpp  51  1   ssl_test
> Предупреждение    5   warning C4389: ==: несоответствие типов со знаком и без знака   c:\uusr\simple_server-master\ssl_test\epoll.cpp 63  1   ssl_test
> Предупреждение    6   warning C4389: ==: несоответствие типов со знаком и без знака   c:\uusr\simple_server-master\ssl_test\epoll.cpp 64  1   ssl_test
> Предупреждение    7   warning C4389: ==: несоответствие типов со знаком и без знака   c:\uusr\simple_server-master\ssl_test\epoll.cpp 65  1   ssl_test

**Comment by 3s3s** [comment]
Похоже, что вы не скачали содержимое директории "https://github.com/3s3s/simple_server/tree/master/curl"
Или эта директория у вас находится в неправильном месте.
Или у вас что-то не так с правами доступа к файлам в этой директории...

Проверьте, существует ли файл c:\uusr\simple_server-master\curl\include\curl\curl.h и есть ли у вашего компилятора права доступа к этому файлу.

**Comment by UUSR** [comment]
@3s3s Всё проверил ещё раз ,директория C:\UUSR\simple_server-master\curl\include\curl\curl.h на месте доступ есть. Компилил на win 10 ,visual studio ultimate 2013. Ума не приложу...

**Comment by UUSR** [comment]
Наверное в свойствах проекта нужно добавить путь к директории...

**Comment by 3s3s** [comment]
Все понял, почему-то curlbuild.h оказался в gitignore.
Сейчас перезалью его в мастер.

**Comment by UUSR** [comment]
@3s3s Спасибо ждём...

**Comment by 3s3s** [comment]
Попробуйте. Файл добавлен. https://github.com/3s3s/simple_server/blob/master/curl/include/curl/curlbuild.h

**Comment by UUSR** [comment]
@3s3s Собирал опять ,теперь не хватает файла "libcurld.lib". Похоже не хватает директории:
`simple_server\ssl_test\LINK`

> Ошибка  99  error LNK1104: не удается открыть файл "libcurld.lib"   C:\UUSR\simple_server\ssl_test\LINK ssl_test

**Comment by 3s3s** [comment]
ОК, завтра еще раз посмотрю.
Сейчас нет под рукой нужной версии студии. На сколько помню там в солюшене два проекта: server и curl.
Чтобы собрался сервер, нужно сначала скомпилировать curl.
Вы кстати можете еще попробовать старые коммиты, там не было зависимостей от curl.
https://github.com/3s3s/simple_server/releases/tag/0.15

**Comment by UUSR** [comment]
@3s3s По этой ветке тоже репозиторий не компилится ,с ошибкой:

> Ошибка  1   error C1083: Не удается открыть файл включение: openssl/rsa.h: No such file or directory   c:\uusr\simple_server-0.15\ssl_test\server.h    26  1   ssl_test
> Предупреждение    2   warning C4245: return: преобразование "int" в "unsigned __int64", несоответствие типов со знаком и без    c:\uusr\simple_server-0.15\ssl_test\sendfile.cpp    33  1   ssl_test
> Предупреждение    3   warning C4245: return: преобразование "int" в "unsigned __int64", несоответствие типов со знаком и без    c:\uusr\simple_server-0.15\ssl_test\sendfile.cpp    40  1   ssl_test
> Предупреждение    4   warning C4245: return: преобразование "int" в "unsigned __int64", несоответствие типов со знаком и без    c:\uusr\simple_server-0.15\ssl_test\sendfile.cpp    51  1   ssl_test
> Предупреждение    5   warning C4389: ==: несоответствие типов со знаком и без знака   c:\uusr\simple_server-0.15\ssl_test\epoll.cpp   63  1   ssl_test
> Предупреждение    6   warning C4389: ==: несоответствие типов со знаком и без знака   c:\uusr\simple_server-0.15\ssl_test\epoll.cpp   64  1   ssl_test
> Предупреждение    7   warning C4389: ==: несоответствие типов со знаком и без знака   c:\uusr\simple_server-0.15\ssl_test\epoll.cpp   65  1   ssl_test

Файл физически лежит по адресу: `C:\UUSR\simple_server-0.15\openssl\include\openssl\rsa.h` но в `server.h` стоит `#include <openssl/rsa.h>       /* SSLeay stuff */` ,похоже studio ищет файл по адресу `C:\UUSR\simple_server-0.15\openssl\` и естественно его не находит...

Жду пока вы поправите..

**Comment by 3s3s** [comment]
В ветке мастер, добавил curl в солюшен, теперь все компилируется вместе. Только нужно, чтобы libcurl скомпилировалась раньше чем все остальное, не знаю где в студии это настраивается...  
Сначала студия может ругнуться на старые файлы проекта - скажите ОК. Сделайте "Rebuild Solution" если ругнется что нет "libcurld.lib", просто сделайте еще раз "Build Solution".
С предыдущим релизом тоже посмотрю - что не так.

**Comment by 3s3s** [comment]
Посмотрел релиз у меня все компилируется без ошибок.
1. Качаю https://github.com/3s3s/simple_server/archive/0.15.zip
2. Распаковываю в "C:\uusr"
3. Запускаю ssl_test.sln
Делаю "Rebuild Solution". 
Получаю "========== Rebuild All: 1 succeeded, 0 failed, 0 skipped =========="

Windows 10
Visual Studio Professional 2013

**Comment by UUSR** [comment]
@3s3s Спасибо ,буду пробовать вечером.

**Comment by 3s3s** [comment]
Нашел ошибку в настройках проекта релиза. Там были локальные пути моего компьютера прописаны ))
Исправленный релиз без curl: https://github.com/3s3s/simple_server/releases/tag/0.16

**Comment by UUSR** [comment]
@3s3s Походу ветка master компилится вроде если репку размещать по адресу `C:\UUSR\simple_server-master` ,если репку компилить из произвольной директории то тогда нужно выполнить сначала `Перестроить решение` и потом снова `Собрать решение` без этих действий `curl` не собирается т.е. не находит библиотеку `libcurld.lib`.
У вас очень много мусора в проекте особенно в директории `curl`.
Вы наверное используете для работы с github клиент под windows ?
Хорошо бы было сделать так ,чтобы openssl  и curl подгружались не из папки проекта а из системы на которой компилится проект ,тогда не будет проблем с обновлением сервера в дальнейшем...

**Comment by 3s3s** [comment]
Да, использую клиент github под Windows. 
При компиляции в Линуксе, эти библиотеки берутся из системы, потому что там они очень просто интегрируются в систему. 
В Windows, к сожалению, эти библиотеки не только не входят, но и скомпилировать их под Windows - задача нетривиальная... Я писал на хабре о своих приключениях - как впервые попытался скомпилировать openssl https://habrahabr.ru/post/211474/

**Comment by UUSR** [comment]
@3s3s Походу ветка https://github.com/3s3s/simple_server/tree/0.16 у меня скомпилилась без проблем только много предупреждений в студио поступило ,с кодом прийдётся ещё много поработать...
буду говорить только про Windows ,я не вижу необходимости компилировать openssl под Windows для проекта ,ведь достаточно просто установить его в систему. Посмотрите по ссылке: 
https://ru.wikipedia.org/wiki/OpenSSL
Версию под Windows можно взять тут:
http://www.slproweb.com/products/Win32OpenSSL.html
В последствии при компиляции студио будет брать библиотеки из операционной системы и не будет проблем с обновлением openssl для проекта в последствии.
Что по поводу клиента github под Windows то я не рекомендую его вообще использовать ,он у вас льёт всё подряд в проект ,лучше всего использовать Team Explorer для Microsoft Visual Studio 2013 ,это в идеале. Но вы также можете использовать Git из командной строки. В проект нужно включать только src и не нужно добавлять остальные файлы которые создаёт студио...
Как использовать openssl в проектах ,статья на хабре: https://habrahabr.ru/post/277935/

**Comment by UUSR** [comment]
@3s3s доброе утро ,если клонировать ваш репозиторий с помощью Team Explorer и открыть прект то в вкладке обозреватель решений видно сразу три проекта вместе: `curl` ,`libcurl` ,`ssl_test`.
