### ISSUE TITLE
Доступ к simple_server из сети

### ISSUE THREAD

**Issue by UUSR** [3s3s/simple_server#4]
@3s3s Уважаемый разработчик ,у меня не получилось получить доступ к серверу из локальной сети. Т. е. если я на локальной машине где запущен сервер захожу на `http://localhost` то доступ есть , а если набираю просто ip адрес ,например `192.168.178.22` ,это ip этой же машины то сервер не реагирует ни как и доступа нет. Так же у меня в сети есть служба DNS на роутере и например по адресу: `zotac.fritz.box` ,это доменное имя этой же машины то в браузере у меня пустая страница.

**Comment by 3s3s** [comment]
Добрый день.
Чтобы сервер был виден, возможно, нужно настроить файрвол на вашем компьютере и на роутере. 
Когда вы в первый раз запускаете сервер, файрвол windows выдает предупреждение с вопросом: "разрешить ли приложению доступ к сети". Если на этом этапе выбрать "запретить", то сервер будет виден только с локальной машины, а из сети виден не будет. 
Можно для теста попробовать отключить файрвол на время и посмотреть - появится ли доступ.
С файрволом роутера все сложнее. Все зависит от модели роутера и от конфигурации локальной сети. Тут я вам вряд ли смогу что-то подсказать...

Ну и обратите внимание, что в коде который в ветке мастер, сервер "слушает" порты 8085 для http и 1111 для https соединений.
https://github.com/3s3s/simple_server/blob/master/ssl_test/serv.cpp#L4

Поэтому правильно вызывать сервер так: http://192.168.178.22:8085
или так: https://192.168.178.22:1111

**Comment by UUSR** [comment]
@3s3s На роутере у меня сто процентов файрвол всё пускает ,я раньше port freigabe настроил и доступ с наружи есть. Вот на локальной машине сейчас отключил файрвол и всё равно пишет в браузере:

> Не удается получить доступ к сайту
> 
> Сайт
>  192.168.178.22 не позволяет установить соединение.
> Попробуйте сделать следующее:
> Обновите страницу.
> Проверьте подключение к Интернету.
> Проверьте настройки прокси-сервера и брандмауэра.

Вот ума не могу приложить наверное нужно перезагрузить после отключения файрвол?

**Comment by 3s3s** [comment]
Глянул код. Совсем забыл, что с какого-то момента я все переделал для работы с протоколом IPv6. На сколько я помню, в Windows 10 служба IPv6 имеет приоритет над IPv4. Может быть поэтому адрес 192.168.178.22 не подходит. Нужен адрес компьютера в формате IPv6.
Если через DNS, то нужно в настройках DNS тоже IPv6 подключить и настроить.

**Comment by UUSR** [comment]
@3s3s так это всё таки на роутере нужно Ipv6 включить?

**Comment by 3s3s** [comment]
Я не знаю, где у вас служба DNS?
В настройках DNS пропишите IPv6 адрес компьютера и попробуйте через DNS имя на него зайти. Не забудьте указывать порт в браузере http://zotac.fritz.box:8085

**Comment by UUSR** [comment]
@3s3s DNS у меня на роутере ,но он на немецком языке ,сейчас буду разбираться.

**Comment by 3s3s** [comment]
Можно попробовать для начала службу IPv6 на компьютере отключить.

**Comment by UUSR** [comment]
@3s3s отключил Ipv6 в сетевых настройках пока результата нет.
Пингуется без проблем:

> C:\Users\UUSR>ping 192.168.178.22
> 
> Обмен
>  пакетами с 192.168.178.22 по с 32 байтами данных:
> Ответ от 192.168.178.22: число байт=32 время<1мс TTL=128
> Ответ от 192.168.178.22: число байт=32 время<1мс TTL=128
> Ответ от 192.168.178.22: число байт=32 время<1мс TTL=128
> Ответ от 192.168.178.22: число байт=32 время<1мс TTL=128
> 
> Статистика
>  Ping для 192.168.178.22:
>     Пакетов: отправлено = 4, получено = 4, потеряно = 0
>     (0% потерь)
> Приблизительное время приема-передачи в мс:
>     Минимальное = 0мсек, Максимальное = 0 мсек, Среднее = 0 мсек

А через браузер глухо всё ,порт не забываю указывать.

**Comment by UUSR** [comment]
@3s3s Походу поставил на тот же комп другой сервер типа http://smallsrv.com/indexr.htm ,работает без проблем. Получается что нет поддержки IPv4 ,а у меня роутер не хочет с IPv6 работать. Как вернуть поддержку IPv4 в этот релиз **simple_server** ?

**Comment by 3s3s** [comment]
Мне пока некогда делать отдельный бранч, да и нужной студии под руками нет.
Можете сами сделать в своей ветке нужные исправления.
https://github.com/3s3s/simple_server/blob/master/ssl_test/server.h#L463
исправить на 

```
        InitListenSocket(nEpoll, nPortTCP, m_ListenEventTCP, socket (AF_INET, SOCK_STREAM, 0));
            InitListenSocket(nEpoll, nPortSSL, m_ListenEventSSL, socket (AF_INET, SOCK_STREAM, 0));
```

https://github.com/3s3s/simple_server/blob/master/ssl_test/server.h#L477
Исправить на

```
            /*[listen_sd](const char on){
                setsockopt(listen_sd, IPPROTO_IPV6, IPV6_V6ONLY, &on, sizeof(on));
                setsockopt(listen_sd, SOL_SOCKET, SO_REUSEADDR, &on, sizeof(on));
            }(1);

            struct sockaddr_in6 sa_serv;
            memset (&sa_serv, '\0', sizeof(sa_serv));
            sa_serv.sin6_family = AF_INET6;
            sa_serv.sin6_addr   = in6addr_any;
            sa_serv.sin6_port   = htons (nPort); /* Server Port number */
            struct sockaddr_in sa_serv;
            memset (&sa_serv, '\0', sizeof(sa_serv));
            sa_serv.sin_family = AF_INET;
            sa_serv.sin_addr.s_addr = htons( INADDR_ANY );
            sa_serv.sin_port    = htons (nPort); /* Server Port number */

```

**Comment by UUSR** [comment]
@3s3s Спасибо ,попробую. Я свою ветку пока не создал ,не могу врубиться в проект пока.

**Comment by UUSR** [comment]
@3s3s Всё собрал ,только эту секцию не нужно добавлять в код:

> struct sockaddr_in6 sa_serv;
>         memset (&sa_serv, '\0', sizeof(sa_serv));
>         sa_serv.sin6_family = AF_INET6;
>         sa_serv.sin6_addr   = in6addr_any;
>         sa_serv.sin6_port   = htons (nPort); /\* Server Port number */

сейчас работает на протоколе IPv4 ,вопрос исчерпан.
Буду компоновать проект с `openssl` и `curl` вынесеными из проекта в операционную систему ,как я писал в [issues 3](https://github.com/3s3s/simple_server/issues/3)
