### ISSUE TITLE
Системные требования для работы simple_server

### ISSUE THREAD

**Issue by UUSR** [3s3s/simple_server#5]
@3s3s Уважаемый разработчик ,как я уже говорил мне удалось скомпилировать и запустить ваш проект. Но у меня есть к Вам несколько вопросов по совместимости сервера с старыми операционными системами которые используют Net Framework ниже версии 4.5 ,т. е. я пока не смог запустить программу на Windows XP например. Программа выдаёт ошибку "Это приложение не есть приложением Win 32". Прошу Вас дать информацию по минимальным требованиям к операционной системе для запуска simple_server.

**Comment by 3s3s** [comment]
Здравствуйте. 
Нет никаких минимальных требований. Сервер работает на всех системах Windows и Linux. Для его работы не нужны никакие дополнительные фреймворки и библиотеки кроме тех, которые есть в репозитории проекта. 
Возможно вы скомпилировали сервер на 64-битной системе, а пытаетесь файл на 32-битной.
Для 32-битной ХР я лично компилирую проект на Visual Studio Express 2010. Но в репозитории настроек для этой студии не выкладываю, потому что она (2010 студия) слишком уж древняя.

**Comment by UUSR** [comment]
@3s3s Здравствуйте.
Компилил на 32 битной системе ,но на старом компе не пускается сервер пишет ошибку "Это приложение не есть приложением Win 32".
![screenshot_2](https://cloud.githubusercontent.com/assets/17599033/14937577/9f690568-0f0b-11e6-8212-6f635ac7e538.png)
Ума не приложу в чём проблема?

**Comment by UUSR** [comment]
@3s3s создал для вашего проекта привлекательное [Wiki](https://github.com/UUSR/web_server/wiki) описание ,возможно это превличёт заинтересованных пользователей. Ещё хорошо бы отдельный сайт создать для рекламы продукта с каким ни буть красивым доменным именем и сайтом на java script.

**Comment by 3s3s** [comment]
Чем компилировали в 32-битной системе?
Как запускаете: из студии или кликом по экзешнику?
Если запускать из студии ошибку выдает?
Посмотрите в опциях компилятора, может там настроена компиляция под 64-битную систему. Нет под рукой 2013 студии, возможно там эта опция стоит по умолчанию.
У меня на 32-битной ХР примерно с таким же процем как у вас работает и даже на более древнем ноуте с ХР home edition работает.

**Comment by UUSR** [comment]
@3s3s Компилировал в 32-битной системе Visual Studio 2013.
Запускаю кликом по экзешнику на машине с Windows XP Sp3.
Студио на этой машине нет.
В опциях компилятора стоит Debug Win32.
![default](https://cloud.githubusercontent.com/assets/17599033/14944456/9976109a-0ff3-11e6-99f3-d088a46efb93.png)
Выдаёт при запуске такую ошибку:
![error](https://cloud.githubusercontent.com/assets/17599033/14944461/c65b197a-0ff3-11e6-9659-8c89de6dc2a0.png)

**Comment by UUSR** [comment]
@3s3s Доброго времени суток ,забыл поставить совместимость в настройках проекта.
![config](https://cloud.githubusercontent.com/assets/17599033/15028482/6d23b012-1249-11e6-857c-f0c0720c763b.png)
Проблема решена.
