### ISSUE TITLE
Ошибки компиляции

### ISSUE THREAD

**Issue by UUSR** [3s3s/simple_server#6]
@3s3s Уважаемый разработчик,
Мне удалось скомпилировать openssl и curl в Windows 10 ([мануал лежит тут](https://github.com/UUSR/web_server/wiki/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D1%81%D1%80%D0%B5%D0%B4%D1%8B) )
Теперь хочу скомпилировать ваш проект с вынесенными openssl и curl в операционную систему.
Подскажите пожалуйста ,я получаю ошибку в файле RequestWorker.h в строке 23
`_mkdir(DB_DIRS, S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH);`
ошибка вида:

> 1>------ Сборка начата: проект: web_server, Конфигурация: Debug Win32 ------
> 1>  serv.cpp
> 1>c:\uusr\web_server\server\requestworker.h(23): error C4996: 'mkdir': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _mkdir. See online help for details.
> 1>          c:\program files\microsoft visual studio 12.0\vc\include\direct.h(140): см. объявление "mkdir"
> 1>  sendfile.cpp
> 1>  epoll.cpp
> 1>  Создание кода...
> ========== Сборка: успешно: 0, с ошибками: 1, без изменений: 0, пропущено: 0 ==========

Что я делаю не так?

**Comment by 3s3s** [comment]
Раньше ведь компилировалось?
Что поменяли?

Попробуйте исправить https://github.com/3s3s/simple_server/blob/master/ssl_test/RequestWorker.h#L9
на 
`#define _mkdir(a, b) _mkdir(a)`

**Comment by UUSR** [comment]
Это предупреждение или ошибка имеет много возможных значений.

Ошибка C4996 может возникнуть, если компилятор обнаружил функцию, помеченную как устаревшая. Функция может не поддерживаться в будущих выпусках. Это предупреждение можно отключить с помощью прагма-директивы warning (см. пример ниже).

Некоторые функции библиотеки CRT и стандартной библиотеки C++ устарели, и им следует предпочесть новые, более безопасные функции. Дополнительные сведения о заменяющей функции см. в документации для устаревшей функции, указанной в сообщении об ошибке. Чтобы отключить предупреждения об устаревших функциях CRT, определите_CRT_SECURE_NO_WARNINGS.

**Comment by 3s3s** [comment]
Ну определите _CRT_SECURE_NO_WARNINGS тогда.

**Comment by UUSR** [comment]
@3s3s в свойствах проекта поставил конфигурацию сборки программы в Release ,определил _CRT_SECURE_NO_WARNINGS.
Поменял 9 строку в RequestWorker.h на:
`#define _mkdir(a, b) _mkdir(a)`
сборка пошла дальше и ошибок стало меньше.

> 1>------ Перестроение всех файлов начато: проект: web_server, Конфигурация: Release Win32 ------
> 1>  epoll.cpp
> 1>  sendfile.cpp
> 1>  serv.cpp
> 1>  sqlite3.c
> 1>server\sqlite\sqlite3.c(33033): error C4996: 'GetVersionExA': объявлен deprecate
> 1>          C:\Program Files\Windows Kits\8.1\Include\um\sysinfoapi.h(433): см. объявление "GetVersionExA"
> ========== Перестроение всех: успешно: 0, с ошибками: 1, пропущено: 0 ==========

теперь проблема в sglite3.c https://github.com/3s3s/simple_server/blob/master/ssl_test/sqlite/sqlite3.c
строка 33033
`}; /* End of the overrideable system calls */`
стоит ковычка и потом комит ,почему ошибку выдаёт?

**Comment by UUSR** [comment]
всё собрал

> 1>------ Сборка начата: проект: web_server, Конфигурация: Release Win32 ------
> 1>  epoll.cpp
> 1>  sendfile.cpp
> 1>  serv.cpp
> 1>  sqlite3.c
> 1>server\sqlite\sqlite3.c(33033): warning C4996: 'GetVersionExA': объявлен deprecate
> 1>          C:\Program Files\Windows Kits\8.1\Include\um\sysinfoapi.h(433): см. объявление "GetVersionExA"
> 1>  Создание кода
> 1>  Создание кода завершено
> 1>  web_server.vcxproj -> C:\UUSR\web_server\Release\web_server.exe
> ========== Сборка: успешно: 1, с ошибками: 0, без изменений: 0, пропущено: 0 ==========

проект собрался с свежей весией openssl и curl ,теперь их можно обновлять не зависимо от проекта ,получил всего одно предупреждение:

> Предупреждение  1   warning C4996: 'GetVersionExA': объявлен deprecate  C:\UUSR\web_server\server\sqlite\sqlite3.c  33033   1   web_server

сейчас посмотрю что получилось
